#!/bin/sh
# check session and select apps in autostart
if [ "$XDG_SESSION_TYPE" = "wayland" ];
   then
       wl-paste --watch clipman store -P --max-items=30 --histpath="/tmp/clipman.json"
   else
       qlipper
fi
