#!/bin/sh
# check session and select apps in autostart
SESSION=$(env |grep SESSION_TYPE|cut -d "=" -f2)
if [ "$SESSION" = "wayland" ];
   then
       swayidle before-sleep swaylock
   else
       xautolock -time 20 -locker i3lock-fancy
fi
