#!/bin/bash
# displays current compositor or WM (X11) in lxqt-panel > custom command

if [[ "$XDG_CURRENT_DESKTOP" == *"sway"* ]]; then
  swaymsg -t get_outputs | grep -i work | awk '{print $2 $3}' | tr -d '",'
elif [[ "$XDG_CURRENT_DESKTOP" == *"Hyprland"* ]]; then
  wayfire -v | awk '{print "Hyprland " $1}'
elif [[ "$XDG_CURRENT_DESKTOP" == *"wayfire"* ]]; then
  wayfire -v | awk '{print "Wayfire " $1}'
elif [[ "$XDG_CURRENT_DESKTOP" == *"labwc"* ]]; then
  labwc -v
elif [[ "$XDG_CURRENT_DESKTOP" == *"kwin_wayland"* ]]; then
  echo kwin_wayland
  #X11
else
   wmctrl -m | grep Name | cut -d: -f2
fi

