#!/bin/sh
# check session and select screenlocker
  if [ "$wayland_compositor" = "kwin_wayland" ];
    then
    echo "kwin screensaver is in duty"
    exit 0
  elif
    [ "$XDG_SESSION_TYPE" = "wayland" ];
   then
       swayidle before-sleep swaylock
   else
       xautolock -time 20 -locker i3lock-fancy
fi
