#!/bin/bash
# Script for multiple layouts in labwc
# labwc > 0.7.1:  ~/.config/labwc/environment.d/keyboard_layout can be used
#
# Display  active layout in lxqt-panel > custom command plugin:
# cat $XDG_CONFIG_HOME/labwc/environment |grep LAYOUT|cut -c 20-21
# Use monospace font and leftclick=/path/to/togglelayout
# Custom shortcut can be added in rc.xml


for lang in it ch us
do
echo "Layout_1=$lang"
Layout_1=$lang
done
LAYOUT_1=it
LAYOUT_2=fr
LAYOUT_3=us



ACTIVE_LAYOUT=$(cat $XDG_CONFIG_HOME/labwc/environment.d/*.env |grep LAYOUT|cut -c 20-21)

cd $XDG_CONFIG_HOME/labwc/environment.d/

if [ $ACTIVE_LAYOUT = $LAYOUT_1 ]; then
	mv $LAYOUT_1.env LAYOUT_1
	mv $LAYOUT_2 $LAYOUT_2.env

elif  [ $ACTIVE_LAYOUT = $LAYOUT_2 ]; then
	mv $LAYOUT_2.env LAYOUT_2
	mv $LAYOUT_3 $LAYOUT_3.env
elif  [ $ACTIVE_LAYOUT = $LAYOUT_3 ]; then
	mv $LAYOUT_3.env $LAYOUT_3
	mv $LAYOUT_1 $LAYOUT_1.env
fi
labwc -r


